
INSERT INTO USERS (USERNAME, PASSWORD,ACTIVATED, VERSION)
VALUES
    ('admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', TRUE, 0),
    ('user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', TRUE, 0)
;

INSERT INTO AUTHORITY (NAME, VERSION)
VALUES
    ('ADMIN', 0),
    ('USER', 0),
    ('BUSINESS', 0)
;

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME)
VALUES
    (1, 'ADMIN'),
    (1, 'USER'),
    (1, 'BUSINESS'),
    (2, 'USER')
;
