create table users (
                          id bigint generated by default as identity,
                          create_time timestamp(6),
                          creator bigint,
                          is_deleted boolean,
                          update_time timestamp(6),
                          updater bigint,
                          version integer not null,
                          activated boolean not null,
                          password varchar(100) not null,
                          username varchar(100) not null,
                          primary key (id)
);
create table authority (
                           name varchar(50) not null,
                           version integer not null,
                           primary key (name)
);
create table user_authority (
                                user_id bigint not null,
                                authority_name varchar(50) not null,
                                primary key (user_id, authority_name)
);

-- 创建钱包表
create table wallet (
                          id bigint generated by default as identity,
                          create_time timestamp(6),
                          creator bigint,
                          is_deleted boolean,
                          update_time timestamp(6),
                          updater bigint,
                          version integer not null,
                          money double precision,
                          userid bigint not null unique,
                          frozen_money double precision,
                          overdraft_limit double precision,
                          overdraft_amount double precision,
                          overdraft_time timestamp(6),
                          is_vip boolean,
                          reward_money double precision,
                          primary key (id)
);

-- 创建交易表
create table transaction (
                          id bigint generated by default as identity,
                          create_time timestamp(6),
                          creator bigint,
                          is_deleted boolean,
                          update_time timestamp(6),
                          updater bigint,
                          version integer not null,
                          money double precision,
                          type integer,
                          fromwallet bigint,
                          towallet bigint,
                          status integer,
                          order_id bigint,
                          description varchar(255),
                          primary key (id)
);
